os:
  - linux
#  - windows
language: cpp
#  - clang

addons:
  apt:
    packages:
      - gcc-avr
      - avr-libc
      - doxygen
      - cppcheck
      - cpputest
      - graphviz
      - libsdl2-dev
before_install:
  - pip install --user cpp-coveralls
install: skip
jobs:
  allow_failures:
    - os: windows
  include:
    - stage: Check esp code
      script:
        - ./.travis/setup_esp_build_env.sh travis
        - . ~/esp/esp-idf/export.sh
        - make -C examples -f Makefile.esp32 PROJECT=demos/ssd1306_demo
      cache:
        directories:
          - /home/travis/esp
          - /home/travis/.espressif
    - stage: Check linux code (gcc)
      compiler: gcc
      script:
        - make docs 1> /dev/null
        - make ARCH=linux EXTRA_CPPFLAGS="--coverage" SDL_EMULATION=y check
      after_success:
        - coveralls -b ./src --exclude docs --exclude unittest --exclude bld --exclude tools --exclude examples --exclude examples_to_do --gcov-options '\-lp'
    - stage: Check avr code
      script:
        - make ARCH=avr SDL_EMULATION=n
    - stage: Check linux code (clang)
      compiler: clang
      script:
        - make ARCH=linux SDL_EMULATION=y check

