version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.6
jobs:
  build:
    # Linux gcc, clang, AVR
    machine:
      image: ubuntu-2004:202101-01
    steps:
      # install dependencies
      - run:
          name: Install apt dependencies
          command: |
            sudo apt update
            sudo apt install -y gcc g++ clang clang-format libsdl2-dev
            sudo apt install -y cppcheck cpputest doxygen avr-libc gcc-avr graphviz
            sudo pip3 install cpp-coveralls
            pip3 install --user cpp-coveralls
      # code checkout
      - checkout
#      - run:
#          name: Pull Submodules
#          command: git submodule init && git submodule update --remote
      # Building
      - run:
          name: Building documentation
          command: make docs 1> /dev/null
      - run:
          name: Building via gcc and running unit tests
          command: make ARCH=linux EXTRA_CPPFLAGS="--coverage" SDL_EMULATION=y check
#      - coveralls/upload
      - run:
          name: Upload coverage statistics
          command: |
             sudo find / -name coveralls
             echo -e "service_name: circle-ci\n" > .coveralls.yml \
             && TRAVIS_JOB_ID="#${CIRCLE_BUILD_NUM}" COVERALLS_REPO_TOKEN=KxXPskywURsRPcsDEgK5eq4sdNncpk6yB coveralls -b ./src \
             --exclude docs --exclude unittest --exclude bld --exclude tools --exclude examples --exclude examples_to_do --gcov-options '\-lp'
#      - store_artifacts:
#          path: embedded/target/bin.elf
#          destination: binary.elf
      - run:
          # CPPFLAGS="-I/usr/include/SDL2" is the workaround for known Ubuntu 20.04 issue
          name: Building via clang
          command: |
            make clean
            CPPFLAGS="-I/usr/include/SDL2" CC=clang CXX=clang++ LD=clang++ make ARCH=linux SDL_EMULATION=y check
            make cppcheck
      - run:
          name: Building for AVR
          command: |
            make clean
            make ARCH=avr SDL_EMULATION=n

# Free plan doesn't have concurrent jobs
#  esp32:
#    machine:
#      image: ubuntu-2004:202101-01
#    steps:
      # install dependencies
#      - run:
#          name: Install apt dependencies
#          command: |
#            sudo apt install -y gcc g++ sudo apt install clang clang-format libsdl2-dev
#            sudo apt install -y cppcheck cpputest doxygen avr-libc gcc-avr graphviz
#            pip install --user cpp-coveralls
      # Install esp32 SDK
      - restore_cache:
          key: ESP32_SDK
      - checkout
      - run:
          name: Install ESP32 SDK
          command: |
            ./.travis/setup_esp_build_env.sh travis
            . ~/esp/esp-idf/export.sh
      - save_cache:
          key: ESP32_SDK
          paths:
            - /home/travis/esp
            - /home/travis/.espressif
      - run:
          name: Building ESP32 code
          command: |
            . ~/esp/esp-idf/export.sh
            make -C examples -f Makefile.esp32 PROJECT=demos/ssd1306_demo

# Orchestrate our job run sequence
workflows:
  version: 2.1
  host_and_esp32:
    jobs:
#      - build
#      - esp32:
#          requires:
#            - build
      - build:
#          context: github
          filters:
            branches:
              only: master
